# Generated by Django 2.0.3 on 2018-03-24 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='YourResolutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.CharField(max_length=100)),
                ('career', models.CharField(max_length=100)),
                ('travel', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='notes',
            name='yourresolution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolution.YourResolutions'),
        ),
    ]
