# Generated by Django 2.0.3 on 2018-03-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='note_content',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notes',
            name='note_title',
            field=models.CharField(max_length=500),
        ),
    ]
